language: ruby
rvm:
  - 2.4.1
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
  - bundle exec rake db:seed RAILS_ENV=test
script:
  - bundle exec rspec
services:
  - postgresql
